# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesteCep():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_testeCep(self):
    self.driver.get("http://localhost:3030/index.htm")
    self.driver.set_window_size(1280, 728)
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("celso")
    self.driver.find_element(By.ID, "email").send_keys("chatinho.celso@gmail.com")
    self.driver.find_element(By.ID, "telefone").click()
    self.driver.find_element(By.ID, "telefone").send_keys("47920007547")
    self.driver.find_element(By.ID, "cep").click()
    self.driver.find_element(By.ID, "cep").send_keys("89218660")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "numero").click()
    self.driver.find_element(By.ID, "numero").send_keys("273")
    self.driver.find_element(By.ID, "complemento").click()
    self.driver.find_element(By.ID, "complemento").send_keys("casa")
    self.driver.find_element(By.ID, "id").click()
    self.driver.find_element(By.ID, "id").send_keys("01")
    self.driver.find_element(By.ID, "cliente").click()
    dropdown = self.driver.find_element(By.ID, "cliente")
    dropdown.find_element(By.XPATH, "//option[. = 'tipo 1']").click()
    self.driver.find_element(By.ID, "post").click()
  
run= TestTesteCep()
run.setup_method()
run.test_testeCep()